return {
	["Inc10"] = "=", --
	["Dec10"] = "-", --
	["Discard"] = "backspace", --
	["Use"] = "return", --
	["BuyAndUse"] = "p", --
	["SelectHand"] = ".", --
	["SelectJokers"] = ";", --
	["SelectConsumeables"] = "'", --
	["SelectPackCards"] = ",", --
	["SelectShopJokers"] = "\\", --
	["SelectShopVouchers"] = "[", --
	["SelectShopBooster"] = "]", --
	["SelectCycleLeft"] = "left", --
	["SelectCycleRight"] = "right", --
	["DeselectAll"] = "/", --
	["Reroll"] = "tab", --
	["Sell"] = "q", --
	["Select0"] = "0", --
	["Select1"] = "1", --
	["Select2"] = "2", --
	["Select3"] = "3", -- 
	["Select4"] = "4", --
	["Select5"] = "5", --
	["Select6"] = "6", --
	["Select7"] = "7", --
	["Select8"] = "8", --
	["Select9"] = "9", --
	["SortSuit"] = "x", --
	["SortRank"] = "z", --
	["PeekDeck"] = "o", --
}