return {
	misc = {
		dictionary = {
			vi_keybind_unset = "Unset",
			vi_keybind_restart = "Any changes will require a manual game restart.",
			vi_keybind_sel = "Select",
			vi_keybind_sel_desc = "Select a card, 0 through 9\nin the current card area",
			vi_keybind_inc10 = "+10",
			vi_keybind_inc10_desc = "Increment the selection index by 10 \n(wraps at edges)",
			vi_keybind_dec10 = "-10",
			vi_keybind_dec10_desc = "Decrement the selection index by 10\n(wraps at edges)",
			vi_keybind_desel = "Deselect",
			vi_keybind_desel_desc = "Deselects all cards",
			vi_keybind_sel_hand = "Hand",
			vi_keybind_sel_hand_desc = "Moves card focus to\nyour current hand",
			vi_keybind_sel_jokers = "Jokers",
			vi_keybind_sel_jokers_desc = "Moves card focus\nto your jokers",
			vi_keybind_sel_consumables = "Consumables",
			vi_keybind_sel_consumables_desc = "Moves card focus\nto your consumables",
			vi_keybind_sel_pack_cards = "Pack",
			vi_keybind_sel_pack_cards_desc = "Moves card focus to the\ncards inside an opened pack",
			vi_keybind_sel_shop = "Shop",
			vi_keybind_sel_shop_desc = "Moves card focus to the top,\nbottom-left, and bottom-right\nareas of the shop, respectively",
			vi_keybind_sel_left = "Cycle <-",
			vi_keybind_sel_left_desc = "Cycles the current\ncard area backwards",
			vi_keybind_sel_right = "Cycle ->",
			vi_keybind_sel_right_desc = "Cycles the current\ncard area forwards",
			vi_keybind_discard = "Discard/Exit",
			vi_keybind_discard_desc = "Discards selected hand\nExits shop\nSkips blind\nSkips pack",
			vi_keybind_use = "Submit",
			vi_keybind_use_desc = "Submits selected cards in hand\nUses selected consumable\nBuys selected shop item\nCashes out of blind eval\nSelects blind",
			vi_keybind_buy_and_use = "Buy & Use",
			vi_keybind_buy_and_use_desc = "Buys and uses selected\nshop consumable",
			vi_keybind_reroll = "Reroll",
			vi_keybind_reroll_desc = "Rerolls shop/boss blind",
			vi_keybind_sell = "Sell",
			vi_keybind_sell_desc = "Sells selected card",
		}
	}
}