[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'engine/controller.lua'
pattern = "if self.text_input_hook then"
position = "before"
payload = '''
if G.keybind_callback then
	G.keybind_callback(key)
	G.keybind_callback = nil
	return
end
'''
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "play_sound('coin6', config.pitch or 1)"
position = "before"
payload = """
G.__vi_safe_to_cash_out = true
"""
match_indent = true